local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 15.0
      publish_frequency: 15.0
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 8
      height: 8
      resolution: 0.05
      footprint: "[[0.219575,0.245], [-0.3955,0.245], [-0.3955,-0.245], [0.219575,-0.245]]"
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 2.58
        cost_scaling_factor: 1.75
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan virtual_obstacle_source
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_max_range: 8.0
          raytrace_max_range: 9.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: False
        virtual_obstacle_source:
          topic: /Local_virtual_wall
          data_type: PointCloud2
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          obstacle_max_range: 100.0
          raytrace_max_range: 101.0
